id: P23A0AE38
initial_creation_type: input
source_metadata:
  Title: Gaṇḍavyūha Sūtram
  Editor: Vaidya, P. L.
  Publisher: The Mithila Institute of Post-Graduate Studies and Research in Sanskrit
    Learning
  Place of Publication: Darbhanga
  Year: '1960'
  1 nidānaparivartaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  2 samantabhadraḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  3 mañjuśrīḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  4 meghaśrīḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  5 sāgarameghaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  6 supratiṣṭhitaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  7 meghaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  8 muktakaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  9 sāradhvajaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  10 āśā:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  11 bhīṣmottaranirghoṣaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  12 jayoṣmāyatanaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  13 maitrāyaṇī:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  14 sudarśanaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  15 indriyeśvaraḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  16 prabhūtā:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  17 vidvān:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  18 ratnacūḍaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  19 samantanetraḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  20 analaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  21 mahāprabhaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  22 acalā:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  23 sarvagāmī:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  24 utpalabhūtiḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  25 vairaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  26 jayottamaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  27 siṃhavijṛmbhitā:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  28 vasumitrā:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  29 veṣṭhilaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  30 avalokiteśvaraḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  31 ananyagāmī:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  32 mahādevaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  33 sthāvarā:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  34 vāsantī:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  35 samantagambhīraśrīvimalaprabhā:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  36 pramuditanayanajagadvirocanā:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  37 samantasattvatrāṇojaḥśrīḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  38 praśāntarutasāgaravatī:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  39 sarvanagararakṣāsaṃbhavatejaḥśrīḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  40 sarvavṛkṣapraphullanasukhasaṃvāsā:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  41 sarvajagadrakṣāpraṇidhānavīryaprabhā:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  42 sutejomaṇḍalaratiśrīḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  43 gopā:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  44 māyā:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  45 surendrābhā:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  46 viśvāmitraḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  47 śilpābhijñaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  48 bhadrottamā:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  49 muktāsāraḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  50 sucandraḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  51 ajitasenaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  52 śivarāgraḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  53 śrīsaṃbhavaḥ śrīmatiśca:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  54 maitreyaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  56 samantabhadracaryāpraṇidhānam:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  55 mañjuśrīḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:02:20.393742'
last_modified_at: '2022-03-08T16:02:20.393757'
